debug: true
config:
    dbs:
        mysql:
            driver: pdo_mysql
            host: 127.0.0.1
            dbname: grechkatoday
            user: root
            password: root
            charset: utf8
    price:
        strategy:
            average: 60
            deviation: 0.6
            retail_rate: 0.52
    cache:
        dir:
            frontend: web/cache
            backend: cache
        public_cdn_url: /cache
        template_cache_time: 1 hour
    template:
        compress: true