debug: false
config:
    dbs:
        mysql:
            driver: pdo_mysql
            host: 127.0.0.1
            dbname: knone_grechkatoday
            user: knone
            password: loekar
            charset: utf8
    price:
        strategy:
            average: 60
            deviation: 0.6
            retail_rate: 0.52